repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
  - repo: https://github.com/ambv/black
    hooks:
      - id: black
        args:
          - [ --config=pyproject.toml ]
